### ISSUE TITLE
When I delete a user is replaced by an anonymous user off 

### ISSUE THREAD

**Issue by Natalee999** [arslancb/clipbucketv2#195]
Hi,
When I delete a user is replaced by an anonymous user off
You too will have this problem in version 2.8 of clipbucket?
the anonymous user has a random name and email type random@mydomain.tld
I mean that the domain of the user's email is replaced with my domain

SCREENSHOT
![8fdc48e5bc_690x206](https://cloud.githubusercontent.com/assets/16898482/12580821/e8833e2c-c432-11e5-85b0-c17988719362.png)

Thanks

**Comment by sakydev** [comment]
Thank you for taking the time to report this issue @Natalee999 

As it appears, fixing this issue won't be a good idea because its not an issue in the first place.

Let's consider a scenario. 

User Dave signs up and uploads 20 videos, creates 10 collections and uploads 30 photos. 

Now once that user has been deleted, CB creates an anonymous user for the sake of saving content from breaking because deleting entire content of any user can cause numerous different problems for webmasters such as broken urls etc.

Now Dave won't be able to login using his credentials but content will still stay secure on your website.

If you must delete entire content of any user, you can simply do advanced search in admin area against that userid and delete in one click.
